"""Tests that the migrations and the models still describe the same schema.

The test suite builds its tables straight from the models, and deployment builds
them from the migrations. Nothing connects those two paths, so a model changed
without a matching migration passes every other test in this repo and then fails
on deploy. This runs the migrations against a throwaway database and asks
Alembic whether anything is still missing.
"""

from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command

BACKEND = Path(__file__).resolve().parents[1]


@pytest.fixture
def alembic_config(tmp_path: Path) -> Config:
    config = Config(BACKEND / "alembic.ini")
    config.set_main_option("script_location", str(BACKEND / "alembic"))
    config.set_main_option("sqlalchemy.url", f"sqlite:///{tmp_path / 'migrated.db'}")
    # Leave the test runner's logging alone.
    config.attributes["configure_logger"] = False
    return config


class TestMigrations:
    def test_upgrade_to_head_produces_the_models_schema(self, alembic_config: Config):
        command.upgrade(alembic_config, "head")

        try:
            command.check(alembic_config)
        except AutogenerateDiffsDetected as drift:
            pytest.fail(f"models and migrations disagree -- missing a migration?\n{drift}")

    def test_every_migration_can_be_undone(self, alembic_config: Config):
        """A migration you cannot reverse is a deployment you cannot roll back."""
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")
