"""youtube views

Revision ID: a3483dcf20fa
Revises: 1eddca4928f4
Create Date: 2026-08-06 15:29:28.567133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = 'a3483dcf20fa'
down_revision: Union[str, Sequence[str], None] = '1eddca4928f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.Text(), nullable=True),
    sa.Column('watched_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_youtube_views_import_id_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_views')),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_youtube_views_user_fingerprint')
    )
    with op.batch_alter_table('youtube_views', schema=None) as batch_op:
        batch_op.create_index('ix_youtube_views_user_channel', ['user_id', 'channel_name'], unique=False)
        batch_op.create_index('ix_youtube_views_user_watched_at', ['user_id', 'watched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_youtube_views_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_views_video_id'))
        batch_op.drop_index('ix_youtube_views_user_watched_at')
        batch_op.drop_index('ix_youtube_views_user_channel')

    op.drop_table('youtube_views')
    # ### end Alembic commands ###
