"""recommendations and discovery runs

Revision ID: 0855f7894013
Revises: 5cc54ab73712
Create Date: 2026-08-02 17:46:13.431914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = '0855f7894013'
down_revision: Union[str, Sequence[str], None] = '5cc54ab73712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('fetched_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('titles_seen', sa.Integer(), nullable=False),
    sa.Column('titles_added', sa.Integer(), nullable=False),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_runs'))
    )
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.create_index('ix_discovery_runs_user_country', ['user_id', 'country'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mood', sa.String(length=16), nullable=False),
    sa.Column('minutes_available', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_recommendations_title_id_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_title_id'), ['title_id'], unique=False)
        batch_op.create_index('ix_recommendations_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendations_user_created')
        batch_op.drop_index(batch_op.f('ix_recommendations_title_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_discovery_runs_user_country')

    op.drop_table('discovery_runs')
    # ### end Alembic commands ###
