"""initial schema

Revision ID: 86bb567b807e
Revises: 
Create Date: 2026-07-30 21:42:36.676877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = '86bb567b807e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_detail', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports'))
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imports_user_id'), ['user_id'], unique=False)

    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jw_node_id', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('imdb_id', sa.String(length=32), nullable=True),
    sa.Column('tmdb_id', sa.String(length=32), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('imdb_score', sa.Float(), nullable=True),
    sa.Column('tmdb_score', sa.Float(), nullable=True),
    sa.Column('tomatometer', sa.Integer(), nullable=True),
    sa.Column('fetched_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_titles')),
    sa.UniqueConstraint('jw_node_id', name=op.f('uq_titles_jw_node_id'))
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_title'), ['title'], unique=False)

    op.create_table('title_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('query_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('query_title', sa.Text(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_title_resolutions_title_id_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_resolutions')),
    sa.UniqueConstraint('user_id', 'query_key', 'kind', name='uq_title_resolutions_query')
    )
    op.create_table('watch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_title', sa.Text(), nullable=False),
    sa.Column('watched_at', UtcDateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.Text(), nullable=True),
    sa.Column('device_type', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_title', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_watch_events_import_id_imports')),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_watch_events_title_id_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watch_events')),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_watch_events_user_fingerprint')
    )
    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_events_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_events_title_id'), ['title_id'], unique=False)
        batch_op.create_index('ix_watch_events_user_watched_at', ['user_id', 'watched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.drop_index('ix_watch_events_user_watched_at')
        batch_op.drop_index(batch_op.f('ix_watch_events_title_id'))
        batch_op.drop_index(batch_op.f('ix_watch_events_title'))

    op.drop_table('watch_events')
    op.drop_table('title_resolutions')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_title'))

    op.drop_table('titles')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_user_id'))

    op.drop_table('imports')
    # ### end Alembic commands ###
