"""watchlist

Revision ID: 1eddca4928f4
Revises: 0855f7894013
Create Date: 2026-08-04 13:42:46.126173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = '1eddca4928f4'
down_revision: Union[str, Sequence[str], None] = '0855f7894013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('added_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('watched_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_watchlist_title_id_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist')),
    sa.UniqueConstraint('user_id', 'title_id', name='uq_watchlist_user_title')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_title_id'), ['title_id'], unique=False)
        batch_op.create_index('ix_watchlist_user_added', ['user_id', 'added_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_user_added')
        batch_op.drop_index(batch_op.f('ix_watchlist_title_id'))

    op.drop_table('watchlist')
    # ### end Alembic commands ###
