"""provider catalogue, subscriptions and offer cache

Revision ID: 5cc54ab73712
Revises: 86bb567b807e
Create Date: 2026-07-31 15:37:58.746864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = '5cc54ab73712'
down_revision: Union[str, Sequence[str], None] = '86bb567b807e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('short_name', sa.String(length=16), nullable=False),
    sa.Column('technical_name', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('monetization_types', sa.JSON(), nullable=False),
    sa.Column('fetched_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('country', 'short_name', name='uq_providers_country_short_name')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_country'), ['country'], unique=False)

    op.create_table('user_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('short_name', sa.String(length=16), nullable=False),
    sa.Column('added_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_providers')),
    sa.UniqueConstraint('user_id', 'country', 'short_name', name='uq_user_providers_subscription')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('provider_short_name', sa.String(length=16), nullable=False),
    sa.Column('monetization_type', sa.String(length=16), nullable=False),
    sa.Column('presentation_type', sa.String(length=8), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('price_string', sa.Text(), nullable=True),
    sa.Column('price_value', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=True),
    sa.Column('available_to', UtcDateTime(), nullable=True),
    sa.Column('fetched_at', UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_offers_title_id_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('title_id', 'country', 'provider_short_name', 'monetization_type', 'presentation_type', name='uq_offers_title_country_provider_offer')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('ix_offers_title_country', ['title_id', 'country'], unique=False)

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offers_fetched_at', UtcDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_column('offers_fetched_at')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offers_title_country')

    op.drop_table('offers')
    op.drop_table('user_providers')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_country'))

    op.drop_table('providers')
    # ### end Alembic commands ###
